"""Create initial tables

Revision ID: c259340aef97
Revises: 
Create Date: 2025-07-10 11:42:37.795903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c259340aef97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('line_user_id', sa.String(length=100), nullable=True),
    sa.Column('line_display_name', sa.String(length=100), nullable=True),
    sa.Column('line_picture_url', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_line_user_id'), 'users', ['line_user_id'], unique=True)
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('default_monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('late_fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('gate_system_enabled', sa.Boolean(), nullable=True),
    sa.Column('visitor_approval_required', sa.Boolean(), nullable=True),
    sa.Column('qr_code_enabled', sa.Boolean(), nullable=True),
    sa.Column('lpr_enabled', sa.Boolean(), nullable=True),
    sa.Column('line_notify_enabled', sa.Boolean(), nullable=True),
    sa.Column('line_notify_token', sa.String(length=255), nullable=True),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('subscription_expires', sa.DateTime(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villages_code'), 'villages', ['code'], unique=True)
    op.create_index(op.f('ix_villages_id'), 'villages', ['id'], unique=False)
    op.create_index(op.f('ix_villages_name'), 'villages', ['name'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.Column('floor', sa.String(length=10), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('size_sqm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ownership_type', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('lease_start_date', sa.DateTime(), nullable=True),
    sa.Column('lease_end_date', sa.DateTime(), nullable=True),
    sa.Column('lease_monthly_rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('electricity_meter', sa.String(length=50), nullable=True),
    sa.Column('water_meter', sa.String(length=50), nullable=True),
    sa.Column('gas_meter', sa.String(length=50), nullable=True),
    sa.Column('internet_enabled', sa.Boolean(), nullable=True),
    sa.Column('access_codes', sa.JSON(), nullable=True),
    sa.Column('key_cards', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('maintenance_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_unit_number'), 'properties', ['unit_number'], unique=False)
    op.create_index(op.f('ix_properties_village_id'), 'properties', ['village_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_village_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_unit_number'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_villages_name'), table_name='villages')
    op.drop_index(op.f('ix_villages_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_code'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_users_line_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
